- Tu viens, Cro ?Magnon s’impatiente devant la hutte où habite son ami. Le gibier ne va pas les attendre éternellement !- J’arrive ! fait une voix ensommeillée.Enfin, l’entrée de la hutte livre passage au deuxième valeureux guerrier. Les cheveux en broussaille, il tient sa lance à l’envers, la pointe en bas.- Attention de ne pas te la planter dans le pied !se moque Cro.
Magnon corrige sa position et, côte à côte, les deux enfants quittent le village. Aujourd’hui, aucun adulte ne les accompagne ! C’est leur première chasse de vrais guerriers !- On cherche quoi ? demande Magnon lorsqu’ils se sont éloignés.- Ce qu’on trouve, pour commencer. Il faut repérer des traces comme les anciens nous l’ont appris.Et, appuyés sur leur lance, la tête penchée en avant, ils se mettent à lire le sol et les broussailles. Ils marchent ainsi longtemps sans rien découvrir.
- Tu sais où on est ? s’inquiète bientôt Magnon.- Non, mais en revenant sur nos pas, on devrait retrouver la rivière.Ce qu’ils font, en s’orientant à l’aide du soleil. Quelques minutes s’écoulent et Cro pousse un grand cri.- Là ! fait-il en désignant deux traces de pas bien ronds dessinées dans de la terre molle. On dirait les empreintes d’un renne !- Suivons-les ! dit Magnon.
Tantôt nettes, tantôt invisibles dans l’herbe, les traces dessinent un chemin compliqué dans la vallée mais ils parviennent à ne pas les perdre de vue. Au détour d’un rocher, la rivière leur barre le chemin.- On va perdre les traces dans l’eau ! s’inquiète Magnon.Après qu’ils ont traversé, Cro le rassure :- Les empreintes ! Regarde, elles sont là ! Mais il est parti où, ce renne, à la fin ! Allez, on court ! La nuit va bientôt tomber !
- Tu viens, Cro ?Magnon s’impatiente devant la hutte où habite son ami. Le gibier ne va pas les attendre éternellement !- J’arrive ! fait une voix ensommeillée.Enfin, l’entrée de la hutte livre passage au deuxième valeureux guerrier. Les cheveux en broussaille, il tient sa lance à l’envers, la pointe en bas.- Attention de ne pas te la planter dans le pied !se moque Cro.
Magnon corrige sa position et, côte à côte, les deux enfants quittent le village. Aujourd’hui, aucun adulte ne les accompagne ! C’est leur première chasse de vrais guerriers !- On cherche quoi ? demande Magnon lorsqu’ils se sont éloignés.- Ce qu’on trouve, pour commencer. Il faut repérer des traces comme les anciens nous l’ont appris.Et, appuyés sur leur lance, la tête penchée en avant, ils se mettent à lire le sol et les broussailles. Ils marchent ainsi longtemps sans rien découvrir.
- Tu sais où on est ? s’inquiète bientôt Magnon.- Non, mais en revenant sur nos pas, on devrait retrouver la rivière.Ce qu’ils font, en s’orientant à l’aide du soleil. Quelques minutes s’écoulent et Cro pousse un grand cri.- Là ! fait-il en désignant deux traces de pas bien ronds dessinées dans de la terre molle. On dirait les empreintes d’un renne !- Suivons-les ! dit Magnon.
Tantôt nettes, tantôt invisibles dans l’herbe, les traces dessinent un chemin compliqué dans la vallée mais ils parviennent à ne pas les perdre de vue. Au détour d’un rocher, la rivière leur barre le chemin.- On va perdre les traces dans l’eau ! s’inquiète Magnon.Après qu’ils ont traversé, Cro le rassure :- Les empreintes ! Regarde, elles sont là ! Mais il est parti où, ce renne, à la fin ! Allez, on court ! La nuit va bientôt tomber !

.
test
